### ISSUE TITLE
Add Swagger docs for `/customcrawl` endpoint

### ISSUE THREAD

**Issue by patcon** [archivers-space/archivers-api#11]
This is beginner task tagged as `first-timers-only`, and is prepared specifically to be taken on by someone who is new to the Data Together project. If this is you: Yay! Welcome aboard! :smile: 

--------------

The API provided by this repo has a [documentation website](https://api.archivers.co/docs/). It is generated from these instructions:
https://github.com/datatogether/api#generating-documentation

It is generated from a formatted YAML file, which describes how a person or program could interact with it. Since the YAML file is written according to the Swagger API spec, using that file can generate documentation and even libraries in many language that will help people talk to the API.

- [`open_api.yaml` config file of GitHub](https://github.com/datatogether/api/blob/master/open_api.yaml)
  - [view in Swagger Editor](https://editor.swagger.io/?url=https://raw.githubusercontent.com/datatogether/api/master/open_api.yaml)

Right now, the `/customcrawl` endpoint that needs documenting is only described in the code itself:
- https://github.com/datatogether/api/blob/fa6335a487826db59da4744c348ce19e48c47dca/server.go#L111-L112
- https://github.com/datatogether/api/blob/master/custom_crawl_handlers.go
- https://github.com/datatogether/core/blob/master/custom_crawl.go#L17

Could someone help us 

----

Reticketed from action item on call: [Data Together Tech Standup 2017-11-16](https://hackmd.io/MYdgTAHAbApgRgQwLRQMwKkgLAgDHJCMYYJMEOAVil0rAS1QBMg=)

**Comment by patcon** [comment]
https://github.com/datatogether/api#generating-documentation

**Comment by patcon** [comment]
https://github.com/datatogether/api/blob/master/open_api.yaml

**Comment by hapr05** [comment]
hi can i take this?

**Comment by patcon** [comment]
@hapr05 👋 hiya!

cc: @b5 (i know it's delayed, but thinking it's good to have a final response anyhow :)

**Comment by MariaTaborda** [comment]
Hi @patcon  is this issue still up for grabs? Would love to help

**Comment by patcon** [comment]
Heyo Maria!

What say you @b5? also, hi hi hi

**Comment by b5** [comment]
Hi @MariaTaborda! Sadly we've made the decision to deprecate this API entirely. Thank you so much for the offer to help, but in this case I'm not sure it would help.

Also, 👋  @patcon! Hope all is well in your neck of the woods 😄

**Comment by b5** [comment]
@MariaTaborda we _are_ however, working on a very similar issue over at another project I work on called Qri. If you're looking to contribute OpenAPI documentation to a go project, a number of us would be _delighted_ to write out an issue on writing improvements to this file: https://github.com/qri-io/qri/blob/master/api/open_api_3.yaml

If you have any interest, just let me know and I'll write an issue you can consider. Here's an example issue of how we like to work with open source contributors: https://github.com/qri-io/frontend/issues/488

Thanks!
